(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var c=this||self;function e(a,l){a=a.split(".");var b=c;a[0]in b||"undefined"==typeof b.execScript||b.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===l?b[d]&&b[d]!==Object.prototype[d]?b=b[d]:b=b[d]={}:b[d]=l}var f=/^[\w+/_-]+[=]{0,2}$/,g=null;function h(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&f.test(a)?a:""}function k(a){return a};var m={0:"Traduzir",1:"Cancelar",2:"Fechar",3:function(a){return"O Google traduziu automaticamente esta p\u00e1gina para: "+a},4:function(a){return"Traduzido para: "+a},5:"Erro: o servidor n\u00e3o conseguiu completar a sua solicita\u00e7\u00e3o. Tente novamente mais tarde.",6:"Saiba mais",7:function(a){return"Powered by "+a},8:"Tradutor",9:"Tradu\u00e7\u00e3o em andamento",10:function(a){return"Traduzir esta p\u00e1gina para: "+(a+" usando o Google Tradutor?")},11:function(a){return"Ver esta p\u00e1gina em: "+
a},12:"Mostrar o original",13:"O conte\u00fado deste arquivo local ser\u00e1 enviado ao Google para tradu\u00e7\u00e3o usando uma conex\u00e3o segura.",14:"O conte\u00fado desta p\u00e1gina segura ser\u00e1 enviado ao Google para tradu\u00e7\u00e3o usando uma conex\u00e3o segura.",15:"O conte\u00fado desta p\u00e1gina da intranet ser\u00e1 enviado ao Google para tradu\u00e7\u00e3o usando uma conex\u00e3o segura.",16:"Selecione o idioma",17:function(a){return"Desativar tradu\u00e7\u00e3o do "+a},18:function(a){return"Desativar para: "+
a},19:"Sempre ocultar",20:"Texto original:",21:"Sugerir uma tradu\u00e7\u00e3o melhor",22:"Sugerir",23:"Traduzir tudo",24:"Restaurar tudo",25:"Cancelar tudo",26:"Traduzir se\u00e7\u00f5es para meu idioma",27:function(a){return"Traduzir tudo para o "+a},28:"Mostrar idiomas originais",29:"Op\u00e7\u00f5es",30:"Desativar tradu\u00e7\u00e3o para este site",31:null,32:"Mostrar tradu\u00e7\u00f5es alternativas",33:"Clique nas palavras acima para ver tradu\u00e7\u00f5es alternativas",34:"Usar",35:"Para reorganizar, arraste usando a tecla Shift",
36:"Clique para ver tradu\u00e7\u00f5es alternativas",37:'Mantenha a tecla "Shift" pressionada, clique e arraste as palavras acima para reordenar a frase.',38:"Agradecemos a pela sua contribui\u00e7\u00e3o ao Google Tradutor.",39:"Gerenciar tradu\u00e7\u00e3o deste site",40:"Clique em uma palavra para ver tradu\u00e7\u00f5es alternativas ou clique duas vezes para editar diretamente",41:"Texto original",42:"Tradutor",43:"Traduzir",44:"Sua corre\u00e7\u00e3o foi enviada.",45:"Erro: o idioma da p\u00e1gina n\u00e3o \u00e9 compat\u00edvel.",
46:"Widget de tradu\u00e7\u00e3o de idiomas"};var n;function p(a,l){this.a=l===q?a:""}var q={};var r=window.google&&google.translate&&google.translate._const;
if(r){var t;a:{for(var u=[],v=[""],w=0;w<v.length;++w){var x=v[w].split(","),y=x[0];if(y){var z=Number(x[1]);if(!(!z||.1<z||0>z)){var A=Number(x[2]),B=new Date,C=1E4*B.getFullYear()+100*(B.getMonth()+1)+B.getDate();!A||A<C||u.push({version:y,ratio:z,b:A})}}}var D=0,E=window.location.href.match(/google\.translate\.element\.random=([\d\.]+)/),F=Number(E&&E[1])||Math.random();for(w=0;w<u.length;++w){var G=u[w];D+=G.ratio;if(1<=D)break;if(F<D){t=G.version;break a}}t="TE_20201130_00"}var H="/element/%s/e/js/element/element_main.js".replace("%s",
t);if("0"==t){var I=" element %s e js element element_main.js".split(" ");I[I.length-1]="main_pt-BR.js";H=I.join("/").replace("%s",t)}if(r._cjlc)r._cjlc(r._pas+r._pah+H);else{var J=r._pas+r._pah+H,K,L="SCRIPT",M=document;L=String(L);"application/xhtml+xml"===M.contentType&&(L=L.toLowerCase());K=M.createElement(L);K.type="text/javascript";K.charset="UTF-8";var N,O;if(void 0===n){var P=null,Q=c.trustedTypes;if(Q&&Q.createPolicy){try{P=Q.createPolicy("goog#html",{createHTML:k,createScript:k,createScriptURL:k})}catch(a){c.console&&
c.console.error(a.message)}n=P}else n=P}var R=(O=n)?O.createScriptURL(J):J;N=new p(R,q);K.src=N instanceof p&&N.constructor===p?N.a:"type_error:TrustedResourceUrl";var S;var T=K.ownerDocument&&K.ownerDocument.defaultView;T&&T!=c?S=h(T.document):(null===g&&(g=h(c.document)),S=g);S&&K.setAttribute("nonce",S);var U=document.getElementsByTagName("head")[0];U||(U=document.body.parentNode.appendChild(document.createElement("head")));U.appendChild(K)}e("google.translate.m",m);e("google.translate.v",t)};}).call(window)
